### ISSUE TITLE
CSS not routed properly in 1.0.22 gem

### ISSUE THREAD

**Issue by swrobel** [neerajsingh0101/admin_data#58]
Javascripts seem to work fine but the pages include css @ /admin_data/public/css/base.css which gives the following routing error when I try to access it:
    The action 'css' could not be found for AdminData::PublicController
As a result the pages are all unstyled.

**Comment by neerajsingh0101** [comment]
Just now. Like 1 minute ago I pushed a new version of gem with lots and lots of changes. It is v 1.1.

Can you check if this problem persists in v1.1 also?

Thanks

**Comment by swrobel** [comment]
Hmm, worse now. It seems that the javascript doesn't route properly either. I see it is looking for the css in /admin_data/public/stylesheets/ now but it still doesn't work.

**Comment by neerajsingh0101** [comment]
fix coming soon.

**Comment by neerajsingh0101** [comment]
try gem version 1.1.1 . It is fixed there.

Thanks for reporting. Appreciate it.

If you have any feedback for admin_data then do let me know.

**Comment by swrobel** [comment]
Really appreciate all of the hard work on this gem, but unfortunately it still doesn't work:
    Started GET "/admin_data/public/javascripts/vendor/jquery-1.4.2.js" for 127.0.0.1 at 2010-12-07 11:37:14 -0800
      Processing by AdminData::PublicController#serve as HTML
      Parameters: {"file"=>"javascripts/vendor/jquery-1.4.2.js"}
    Completed 404 Not Found in 219ms (Views: 1.8ms | ActiveRecord: 2.4ms)

```
Started GET "/admin_data/public/stylesheets/base.css" for 127.0.0.1 at 2010-12-07 11:37:02 -0800
AbstractController::ActionNotFound (The action 'stylesheets' could not be found for AdminData::PublicController):
Rendered /usr/local/lib/ruby/gems/1.9.1/gems/actionpack-3.0.3/lib/action_dispatch/middleware/templates/rescues/unknown_action.erb within rescues/layout (1.5ms)
```

**Comment by neerajsingh0101** [comment]
So it seems when I use :path in Gemfile then it works but not with gem as we use gem. I have fixed it and waiting for gemcutter to index v1.1.2. will test with that and then will update you.

sorry about the trouble.

**Comment by neerajsingh0101** [comment]
It is working with version 1.1.3. Try it. :-)

**Comment by swrobel** [comment]
Back to where we started with 1.1.3: javascript works, but css does not. Same error as in my last message.

**Comment by neerajsingh0101** [comment]
Can you post what you are seeing in your log message? If you want you can IM me . I am neerajdotname on all major IMs.

http://admin-data-test.heroku.com/admin_data is rendering css fine and it is running on v1.1.3 https://github.com/neerajdotname/admin_data_test/blob/master/Gemfile#L13

One thing I noticed that you are running ruby 1.9. I am on 1.8.7. Although that should not matter.

**Comment by neerajsingh0101** [comment]
Also can you post the html code you see in the <HEAD> in the rendered html response. thanks

**Comment by neerajsingh0101** [comment]
Closing this ticket since the issue was routing.
